/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { SegmentService } from "../segment.service";
import { SegmentCreateInput } from "./SegmentCreateInput";
import { SegmentWhereInput } from "./SegmentWhereInput";
import { SegmentWhereUniqueInput } from "./SegmentWhereUniqueInput";
import { SegmentFindManyArgs } from "./SegmentFindManyArgs";
import { SegmentUpdateInput } from "./SegmentUpdateInput";
import { Segment } from "./Segment";

export class SegmentGrpcControllerBase {
  constructor(protected readonly service: SegmentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Segment })
  @GrpcMethod("SegmentService", "createSegment")
  async createSegment(
    @common.Body() data: SegmentCreateInput
  ): Promise<Segment> {
    return await this.service.createSegment({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Segment] })
  @ApiNestedQuery(SegmentFindManyArgs)
  @GrpcMethod("SegmentService", "segments")
  async segments(@common.Req() request: Request): Promise<Segment[]> {
    const args = plainToClass(SegmentFindManyArgs, request.query);
    return this.service.segments({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Segment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SegmentService", "segment")
  async segment(
    @common.Param() params: SegmentWhereUniqueInput
  ): Promise<Segment | null> {
    const result = await this.service.segment({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Segment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SegmentService", "updateSegment")
  async updateSegment(
    @common.Param() params: SegmentWhereUniqueInput,
    @common.Body() data: SegmentUpdateInput
  ): Promise<Segment | null> {
    try {
      return await this.service.updateSegment({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Segment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SegmentService", "deleteSegment")
  async deleteSegment(
    @common.Param() params: SegmentWhereUniqueInput
  ): Promise<Segment | null> {
    try {
      return await this.service.deleteSegment({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
