/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { ContextService } from "../context.service";
import { ContextCreateInput } from "./ContextCreateInput";
import { ContextWhereInput } from "./ContextWhereInput";
import { ContextWhereUniqueInput } from "./ContextWhereUniqueInput";
import { ContextFindManyArgs } from "./ContextFindManyArgs";
import { ContextUpdateInput } from "./ContextUpdateInput";
import { Context } from "./Context";

export class ContextGrpcControllerBase {
  constructor(protected readonly service: ContextService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Context })
  @GrpcMethod("ContextService", "createContext")
  async createContext(
    @common.Body() data: ContextCreateInput
  ): Promise<Context> {
    return await this.service.createContext({
      data: data,
      select: {
        createdAt: true,
        data: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Context] })
  @ApiNestedQuery(ContextFindManyArgs)
  @GrpcMethod("ContextService", "contexts")
  async contexts(@common.Req() request: Request): Promise<Context[]> {
    const args = plainToClass(ContextFindManyArgs, request.query);
    return this.service.contexts({
      ...args,
      select: {
        createdAt: true,
        data: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Context })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ContextService", "context")
  async context(
    @common.Param() params: ContextWhereUniqueInput
  ): Promise<Context | null> {
    const result = await this.service.context({
      where: params,
      select: {
        createdAt: true,
        data: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Context })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ContextService", "updateContext")
  async updateContext(
    @common.Param() params: ContextWhereUniqueInput,
    @common.Body() data: ContextUpdateInput
  ): Promise<Context | null> {
    try {
      return await this.service.updateContext({
        where: params,
        data: data,
        select: {
          createdAt: true,
          data: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Context })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ContextService", "deleteContext")
  async deleteContext(
    @common.Param() params: ContextWhereUniqueInput
  ): Promise<Context | null> {
    try {
      return await this.service.deleteContext({
        where: params,
        select: {
          createdAt: true,
          data: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
