/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AiResponse } from "./AiResponse";
import { AiResponseCountArgs } from "./AiResponseCountArgs";
import { AiResponseFindManyArgs } from "./AiResponseFindManyArgs";
import { AiResponseFindUniqueArgs } from "./AiResponseFindUniqueArgs";
import { DeleteAiResponseArgs } from "./DeleteAiResponseArgs";
import { AiResponseService } from "../aiResponse.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AiResponse)
export class AiResponseResolverBase {
  constructor(
    protected readonly service: AiResponseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AiResponse",
    action: "read",
    possession: "any",
  })
  async _aiResponsesMeta(
    @graphql.Args() args: AiResponseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AiResponse])
  @nestAccessControl.UseRoles({
    resource: "AiResponse",
    action: "read",
    possession: "any",
  })
  async aiResponses(
    @graphql.Args() args: AiResponseFindManyArgs
  ): Promise<AiResponse[]> {
    return this.service.aiResponses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AiResponse, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AiResponse",
    action: "read",
    possession: "own",
  })
  async aiResponse(
    @graphql.Args() args: AiResponseFindUniqueArgs
  ): Promise<AiResponse | null> {
    const result = await this.service.aiResponse(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AiResponse)
  @nestAccessControl.UseRoles({
    resource: "AiResponse",
    action: "delete",
    possession: "any",
  })
  async deleteAiResponse(
    @graphql.Args() args: DeleteAiResponseArgs
  ): Promise<AiResponse | null> {
    try {
      return await this.service.deleteAiResponse(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
